DROP TABLE IF EXISTS covid, masks, cdc, covidtracking_current, covidtracking_all, county;

-- Create Tables
CREATE TABLE covid (
    date VARCHAR,
    county TEXT,
    state TEXT,
    fips INT,
    cases INT,
    deaths INT,
    PRIMARY KEY (date, fips)
);

CREATE TABLE masks (
    fips INT PRIMARY KEY,
    never FLOAT,
    rarely FLOAT,
    sometimes FLOAT,
    frequently FLOAT,
    always FLOAT
);

CREATE TABLE cdc (
    state TEXT,
    year INT,
    week INT,
    week_ending_date VARCHAR,
    all_causes INT,
    natural_causes INT,
    septicemia INT,
    malignant_neoplasms INT,
    diabetes INT,
    alzheimers INT,
    influenza_and_pneumonia INT,
    chronic_lower_respiratory INT,
    other_diseases_of_respiratory INT,
    nephritis_nephrotic_syndrome INT,
    symptoms_signs_and_abnormal INT,
    diseases_of_heart INT,
    cerebrovascular_diseases INT,
    covid_19_multiple_causes INT,
    covid_19_underlying_cause INT,
    flag_otherresp VARCHAR,
    flag_otherunk VARCHAR,
    flag_nephr VARCHAR,
    flag_inflpn VARCHAR,
    flag_cov19mcod VARCHAR,
    flag_cov19ucod VARCHAR,
    flag_sept VARCHAR,
    flag_diab VARCHAR,
    flag_alz VARCHAR,
    flag_clrd VARCHAR,
    flag_stroke VARCHAR,
    flag_hd VARCHAR,
    flag_neopl VARCHAR,
    flag_allcause VARCHAR,
    flag_natcause VARCHAR,
    PRIMARY KEY (state, week, year)
);

CREATE TABLE covidtracking_current (
    date INT,
    state TEXT,
    positive INT,
    negative INT,
    pending INT,
    totalTestResults INT,
    hospitalizedCurrently INT,
    hospitalizedCumulative INT,
    inIcuCurrently INT,
    inIcuCumulative INT,
    onVentilatorCurrently INT,
    onVentilatorCumulative INT,
    recovered INT,
    dataQualityGrade VARCHAR,
    lastUpdateEt VARCHAR,
    dateModified VARCHAR,
    checkTimeEt VARCHAR,
    death INT,
    hospitalized INT,
    dateChecked VARCHAR,
    totalTestsViral INT,
    positiveTestsViral INT,
    negativeTestsViral INT,
    positiveCasesViral INT,
    deathConfirmed INT,
    deathProbable INT,
    totalTestEncountersViral INT,
    totalTestsPeopleViral INT,
    totalTestsAntibody INT,
    positiveTestsAntibody INT,
    negativeTestsAntibody INT,
    totalTestsPeopleAntibody INT,
    positiveTestsPeopleAntibody INT,
    negativeTestsPeopleAntibody INT,
    totalTestsPeopleAntigen INT,
    positiveTestsPeopleAntigen INT,
    totalTestsAntigen INT,
    positiveTestsAntigen INT,
    fips INT,
    positiveIncrease INT,
    negativeIncrease INT,
    total INT,
    totalTestResultsSource TEXT,
    totalTestResultsIncrease INT,
    posNeg INT,
    deathIncrease INT,
    hospitalizedIncrease INT,
    hash VARCHAR,
    commercialScore INT,
    negativeRegularScore INT,
    negativeScore INT,
    positiveScore INT,
    score INT,
    grade VARCHAR,
    PRIMARY KEY (state, date)
);

CREATE TABLE covidtracking_all (
    date INT PRIMARY KEY,
    states INT,
    positive INT,
    negative INT,
    pending INT,
    hospitalizedCurrently INT,
    hospitalizedCumulative INT,
    inIcuCurrently INT,
    inIcuCumulative INT,
    onVentilatorCurrently INT,
    onVentilatorCumulative INT,
    recovered INT,
    dateChecked VARCHAR,
    death INT,
    hospitalized INT,
    totalTestResults INT,
    lastModified VARCHAR,
    total INT,
    posNeg INT,
    deathIncrease INT,
    hospitalizedIncrease INT,
    negativeIncrease INT,
    positiveIncrease INT,
    totalTestResultsIncrease INT,
    hash VARCHAR
);

CREATE TABLE county (
    state TEXT,
    fips INT PRIMARY KEY,
    county TEXT,
    county_seat TEXT,
    lat FLOAT,
    lon FLOAT
);